#index:
#    path: /
#    controller: App\Controller\DefaultController::index

contatos:
  path: contatos
  controller: App\Controller\ContatosController::index

promotores:
    path: promotores
    controller: App\Controllers\PromotoresController::index

produtos:
    path: produtos
    controller: App\Controllers\ProdutosController::index
    